version: '3.8'

services:
    # --- BASES DE DATOS ---
    reservas-db:
        image: mysql:8.0
        container_name: elbuensabor_mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootroot
            MYSQL_DATABASE: elbuensabor_db
            MYSQL_USER: redStak
            MYSQL_PASSWORD: qu1Nch1nK
            MYSQL_ROOT_HOST: '%' # Permite conexiones desde cualquier IP de la red Docker
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - elbuensabor_network

    usuarios-db:
        # Instrucción 2: Cambio de Postgres a MongoDB
        image: mongo:latest
        container_name: elbuensabor_mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - mongo_data:/data/db
        ports:
            - "27017:27017"
        networks:
            - elbuensabor_network

    # --- INFRAESTRUCTURA ---
    rabbitmq:
        # Instrucción 4: Servidor de mensajería para auditoría
        image: rabbitmq:3-management
        container_name: elbuensabor_rabbitmq
        ports:
            - "5672:5672"   # Comunicacion microservicios
            - "15672:15672" # Panel: http://192.168.100.3:15672
        networks:
            - elbuensabor_network

    discovery:
        build:
            context: ./discovery
            dockerfile: dockerfile
        ports:
            - "8761:8761"
        networks:
            - elbuensabor_network

    # --- GATEWAY Y BALANCEO ---
    gateway:
        build:
            context: ./gateway
            dockerfile: dockerfile
        # Instrucción 5: Dos instancias del Gateway
        deploy:
            replicas: 2
        depends_on:
            - discovery
        networks:
            - elbuensabor_network

    nginx:
        # Instrucción 6: Doble balanceo de carga
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80" # Acceso: http://192.168.100.3:8080
        depends_on:
            - gateway
        networks:
            - elbuensabor_network

    # --- MICROSERVICIOS ---
    reservation-service:
        build:
            context: ./reservas
            dockerfile: dockerfile
        # Instrucción 3: Más de una instancia sin duplicar proyecto
        deploy:
            replicas: 2
        depends_on:
            - reservas-db
            - discovery
            - rabbitmq
        networks:
            - elbuensabor_network

    user-service:
        build:
            context: ./usuario
            dockerfile: dockerfile
        # Instrucción 3: Más de una instancia
        deploy:
            replicas: 2
        depends_on:
            - usuarios-db
            - discovery
            - rabbitmq
        networks:
            - elbuensabor_network

volumes:
    mongo_data:
    mysql_data:

networks:
    elbuensabor_network:
        driver: bridge