events {
    worker_connections 1024;
}

http {
    # El resolver es la IP del DNS interno de Docker (127.0.0.11).
    # Es VITAL para que Nginx encuentre los Gateways dinámicamente.
    resolver 127.0.0.11 valid=5s;

    # Definimos el grupo de Gateways (Nivel 1 de HA)
    upstream gateway_cluster {
        # Docker DNS devolverá las IPs de todas las réplicas de 'gateway-service'
        server gateway:9091 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;

        location / {
            # USAR UNA VARIABLE es el truco para que Nginx NO falle al arrancar
            # si el servicio no está listo todavía.
            set $backend "http://gateway_cluster";
            proxy_pass $backend;

            # CONFIGURACIÓN DE FAILOVER (Conmutación por error)
            # Si un Gateway falla, intenta con el otro automáticamente.
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
            proxy_connect_timeout 2s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}