spring.application.name=user-service

#Puerto de la aplicación
server.port=0

# Configuración de la conexión a MongoDB
spring.mongodb.uri=mongodb://admin:root@192.168.100.3:27017/elbuensabor_db?authSource=admin

# Configuración de conexión a RabbitMQ (Instrucción 4)
# Apuntando a tu IP local física
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

# Eureka client
eureka.client.service-url.defaultZone=http://discovery:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Forzar el uso de la IP local en el servidor de descubrimiento
eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=192.168.100.3
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Enable displaying Actuator endpoints in the OpenAPI documentation
springdoc.show-actuator=true

# Expose 'openapi' and 'swagger-ui' endpoints under the /actuator base path
management.endpoints.web.exposure.include=health,info,openapi,swagger-ui
